[project]
name = "rpathlib"
version = "0.1.0"
description = "An RClone-powered pathlib implementation"
readme = "README.md"
requires-python = ">=3.9.0"
dependencies = [
    "aiohttp>=3.13.2",
]

[dependency-groups]
dev = [
    "pytest>=8",
    "pytest-asyncio>=1.2.0",
]
