[project]
name = "rpathlib"
version = "0.1.0"
description = "An RClone-powered pathlib implementation"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "aiohttp>=3.13.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]
